### PR TITLE
item count on panel

### PR DESCRIPTION
**Pull request by manjeetaR**
This PR addresses issue #12 

- A Batch with count is added against each of the saved items.

### CODE REVIEW

**Comment by carolinaknoll** [comment]
Hello, @manjeetaR! 

Thank you for your contribution! 🎉 

I have reviewed your changes and they look great! However, they have some merge conflicts that need to be solved. 

Could you please do that so that we can merge your PR? 

Thank you! 😄

**Review by carolinaknoll — CHANGES_REQUESTED** [review]
Hello, @manjeetaR! 

Thank you for your contribution! 🎉 

I have reviewed your changes and they look great! However, they have some merge conflicts that need to be solved. 

Could you please do that so that we can merge your PR? 

Thank you! 😄

**Comment by manjeetaR** [comment]
> Hello, @manjeetaR!
> 
> Thank you for your contribution! 🎉
> 
> I have reviewed your changes and they look great! However, they have some merge conflicts that need to be solved.
> 
> Could you please do that so that we can merge your PR?
> 
> Thank you! 😄

Hi @carolinaknoll,
     Have resolved the conflicts, you may review and merge. Thank you.

**Review by carolinaknoll — APPROVED** [review]

**Comment by carolinaknoll** [comment]
Awesome, thank you very much! 🚀

**Pull request merged**
